
function invoke_target_callbacks(callback_name, CACHE, entity_table, ...)
	local entity_table = entity_table or CACHE.target
	local targets_set = {}
	
	for k, entity in pairs(entity_table) do
		if entity.target and not targets_set[entity.target] then
			targets_set[entity.target] = true
			local target_tbl = igi_taskdata.get_target_table(entity.target)
			if target_tbl[callback_name] then
				target_tbl[callback_name](CACHE, ...)
			end
		end
	end
end